config/routes.rb
Omrails::Application.routes.draw do
  
  get "users/show"

  

as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses

  resources :pins

  devise_for :users, skip: [:sessions]

 resources :users

 resources :user_friendships

  get 'about' => "pages#about"

  root :to => 'pins#index'
  
   get '/:id', to: 'users#show', as: :user

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :image_remote_url


  validates :description, presence: true 
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
  								content_type: {content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/pdf'] },
  								size: {less_than: 100.megabytes}
    

  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>"}


  def image_remote_url=(url_value)
    self.image = URI.parse(url_value) unless url_value.blank?
    super  
  end




  #require 'open-uri'

  #attr_accessible :image_url
  
  #attr_accessor :image_url
  
  #attr_accessible :image_remote_url
  
  
  #before_validation :download_remote_image, :if => :image_url_provided?

  #validates_presence_of :image_remote_url, :if => :image_url_provided?, :message => 'is invalid or inaccessible'
    
#private
  
  #def image_url_provided?
  #end
  
  #def download_remote_image
   # self.image = do_download_remote_image
   # self.image_remote_url = image_url
 # end
  
 # def do_download_remote_image
  #  io = open(URI.parse(image_url))
  #  def io.original_filename; base_uri.path.split('/').last; end
  #  io.original_filename.blank? ? nil : io
  #rescue # catch url errors with validations instead of exceptions (Errno::ENOENT, OpenURI::HTTPError, etc...)
 # end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
 before_filter :authenticate_user!, except: [:index]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(10)
    @pin = Pin.new

    
    @statuses = Status.order("created_at desc")
      
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js
    end

  end
def find
  @pin = Pin.new
end
  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to pins_path, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
   
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<% @pin = Pin.new if @pin.nil? %>
<%= simple_form_for(@pin, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>


   <%= f.input :image, label: "Upload an Image" %>
   <%= f.input :image_remote_url, label: "or enter a URL" %>
    <%= f.input :description, as: :text, input_html: {rows: "3"} %>
  

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box" >
	<%= link_to (image_tag pin.image(:medium)), pin %>
	<p class="description">
		<%= pin.description %>
   </p>
   <p>
   	<strong>
   		Posted by: <%= pin.user.try(:first_name) %> <%=link_to pin.user.try(:biz_name), pin.user %>
   	</strong>	
   </p>
	
	   <% if current_user == pin.user %>
	<p>   
		<%= link_to 'Edit', edit_pin_path(pin) %> |
		<%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
	</p>	
	<% end %>
</div>	

app/views/pins/edit.html.erb
<div class="row">
  <div class="span6 offset3">
   <div class="well">
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>
</div>
</div>
</div>

app/views/pins/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <div class="page-header">
      	   <h3>Statuses</h3>
 <% if @statuses %>
<% @statuses.each do |status| %>
    <div class="status">
      <%= link_to image_tag(status.user.gravatar_url), user_path(status.user) %>
      <%= status.content %>
      <br>
      <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
    </div>
    <% end %>
  <% end %>

</div>
</div>

    <div class="span10">
     <%= render 'pages/home'%>

 <div id="pins" >
<% if @pins %> <%= render @pins %> <% end %>
 
  </div>
 
    </div>
  </div>
</div>
 <%= will_paginate @pins %>

app/views/pins/index.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
  $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<div class="row">
  <div class="span6 offset3">
   <div class="well">
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

</div>
</div>
</div>

app/views/pins/show.html.erb
<div class="row">
  <div class="span6 offset3">
   <div class="well">	
   <%= image_tag @pin.image %>	
	<p>
	  <%= @pin.description %>
	</p>
	<p>
	  <%= @pin.user.biz_name %>
	</p>
		<% if current_user == @pin.user %>
		<%= link_to 'Edit', edit_pin_path(@pin) %> |
		<% end %>
	    <%= link_to 'Back', pins_path %>
   </div>	
  </div>
</div>