config/routes.rb
Omrails::Application.routes.draw do
  
  get "users/show"

  

as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses

  resources :pins

  devise_for :users, skip: [:sessions]

 resources :users

 resources :user_friendships

  get 'about' => "pages#about"

  root :to => 'pins#index'
  
   get '/:id', to: 'users#show', as: :user

end

app/models/user.rb
class User < ActiveRecord::Base

 
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :biz_name
                    validates :first_name, presence: true
                    validates :last_name, presence: true
                    validates :biz_name, presence: true, 
                                         uniqueness: true,
                                         format: {
                                                  with: /^[a-zA-Z0-9_-]+$/,
                                                  message: 'Must be formatted correctly.(Try no spaces)'
                                                        }
                                      




  # attr_accessible :title, :body
  



  has_many :pins, dependent: :destroy
  has_many :statuses, dependent: :destroy
  has_many :user_friendships
  has_many :friends, through: :user_friendships,
                     conditions: {user_friendships: {state: 'accepted'}} 

  has_many :pending_user_friendships, class_name: 'UserFriendship',
                                      foreign_key: :user_id, 
                                      conditions: {state: 'pending'} 

  has_many :pending_friends, through: :pending_user_friendships, source: :friend    

   has_many :requested_user_friendships, class_name: 'UserFriendship',
                                      foreign_key: :user_id,
                                      conditions: { state: 'requested' }
  has_many :requested_friends, through: :requested_user_friendships, source: :friend
  
  has_many :blocked_user_friendships, class_name: 'UserFriendship',
                                      foreign_key: :user_id,
                                      conditions: { state: 'blocked' }
  has_many :blocked_friends, through: :blocked_user_friendships, source: :friend
  
  has_many :accepted_user_friendships, class_name: 'UserFriendship',
                                      foreign_key: :user_id,
                                      conditions: { state: 'accepted' }
  has_many :accepted_friends, through: :accepted_user_friendships, source: :friend                                                 

  

 def to_param
  biz_name
end

 def full_name
    first_name + " " + last_name
  end

   def first_biz_name
    first_name + "(" + biz_name + ")"
  end

  def gravatar_url
  stripped_email = email.strip
  downcased_email = stripped_email.downcase
  hash = Digest::MD5.hexdigest(downcased_email)

  "http://gravatar.com/avatar/#{hash}?s=25"
end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def show
  @user_friendships = current_user.user_friendships.all
    @user = User.find_by_biz_name(params[:id])
     @pins = @user.pins(params[:id]).order("created_at desc").page(params[:page]).per_page(10)
  
     
   
    if @user
      @statuses = @user.statuses.order("created_at desc")
      render action: :show
      
      else
      render file: 'public/404', status: 404, formats: [:html]
   
    end
  end
end





  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="span5">
      <div class="well">
     <div class="page-header">
       
          <% if current_user == @user %>
        	<h1><%= link_to image_tag(@user.gravatar_url)+ ' ', user_path %><%= @user.biz_name %></h1>
                
                <%= @user.full_name %> <br />
                <%= link_to "Edit Profile", edit_user_registration_path %>
          
             <div class="dropdown">

              <h1>
              <a class="dropdown-toggle btn-small btn btn-info" data-toggle="dropdown" href="#">Post A Status</a>
              <a href="#myModal1" role="button" class="btn btn-small btn-info" data-toggle="modal">Pin +</a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">

               <%= render 'statuses/toggle_form' %></h1>
              </ul>
              
            </div>
          <% else %>
          <h1><%= link_to image_tag(@user.gravatar_url)+' ', user_path %><%= @user.biz_name %> <%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'btn'%>
          </h1>
          <% end %>

     </div>

    </div>

   </div>
       
        <div class="span6">
        
          <% if @statuses %>
             <% @statuses.each do |status| %>
                <div class="status">
                  <%= link_to image_tag(status.user.gravatar_url, :size => 15), user_path(status.user) %>
                  <%= status.content %>
                  <br>
                  <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
                  <span class="admin">
              <% if current_user == status.user %>
            | <%= link_to 'Edit', edit_status_path(status) %> |
              <%= link_to 'Delete', status, method: :delete, data: { confirm: 'Are you sure?' } %>
               </span>
                <% end %>
          </div>
         

          <% end %>
        <% end %>

      </div>

 </div>
</div>



<!--<div class="container-fluid">
  <div class="row-fluid">
    <div class="span4">
      
     
      <% if current_user == @user %>
      <h3>Post your Comment</h3>
      <% @status = Status.new if @status.nil? %>

      <%= simple_form_for(@status, html: {class: ""}) do |f| %>
      <%= f.error_notification %>

    <div class="">
    
      <%= f.text_area :content,  placeholder: "Hows business today?", label: "Stati Box", :cols => "200", :rows => "4" %>
    </div>

    <div class="">
      <%= f.button :submit, class: "btn-small btn-primary" %>
    </div>
      
  <% end %>
<% end %> 


  <% if current_user == @user %>
  <h3>I got me some friends</h3>
  <% @user_friendships.each do |friendship| %>
  <% friend = friendship.friend %>
  <div id="<%= dom_id(friendship) %>" class="friend row">
    <div class="span1 offset1">

          <%= link_to image_tag(friend.gravatar_url), user_path(friend.biz_name) %>  
        </div>

        <span class="admin">
           <strong> <%= link_to friend.biz_name, user_path(friend.biz_name) %></strong> | <%= link_to 'edit',edit_user_friendship_path(friendship.friend.biz_name) %>
        </span>
     </div> 
 <% end %>
<% end %>
</div>


   

 
    <div class="span8">
      <h3>Statuses</h3>
       <% if @statuses %>
       <% @statuses.each do |status| %>
    <div class="well">
      <%= link_to image_tag(status.user.gravatar_url), user_path(status.user) %>
      <%= status.content %>
      <br>
      <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
    </div>
    <% end %>
  <% end %>

      
    </div>
  </div>
</div>-->
<div class="span12">
  <div class="row">
<% if @pins %>
<h1><%= @user.biz_name %></h1>

<div id="pins">
  <%= render @pins %>
</div>
</div>
</div>
<% end %>
 <%= will_paginate @pins %>

app/views/users/show.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
  $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
  $('.pagination').remove();
<% end %>