config/routes.rb
Omrails::Application.routes.draw do
  
  get "users/show"

  

as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses

  resources :pins

  devise_for :users, skip: [:sessions]

 resources :users

 resources :user_friendships

  get 'about' => "pages#about"

  root :to => 'pins#index'
  
   get '/:id', to: 'users#show', as: :user

end

app/views/layouts/_footer.html.erb
<div class="footer">
		  <small>
		    <%= link_to "", "#" %>
		   <%= link_to "", "#" %>
		  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar-wrapper">

 <div class="container">
  <div class="navbar navbar-inverse">
   <div class="navbar-inner">
    
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "EntreCommunity", root_path, class: "brand" %>
	      <div class="nav-callapse">
	      	<ul class="nav">
	 
				    <li> <%= link_to "Home", root_path %></li>
				    <li> <%= link_to "About", about_path %></li>
            <li> <%= link_to "", about_path %></li>
            

			</ul>
      
         
          <ul class="nav pull-right">
            <% if user_signed_in? %>
                  
 

                  <li><a data-target="#myModal1" href="#" role="button" data-toggle="modal">Add +</a></li>
                  <!--<li><a data-target="#myModal" href="#" role="button" data-toggle="modal">Add S</a></li>-->
                   <li> <%= link_to "friends", user_friendships_path %></li>
                   <li> <%= link_to "Statuses", statuses_path %></li>
                  <li> <%= link_to "profile", user_path(current_user) %></li>
                  <li><%= link_to "Logout", logout_path, method: :delete %></li>
                  <% else %>
                      <li> <%= link_to "Registration", register_path %></li>
                      <li><%= link_to "Login", login_path %></li>
                  <% end %>
                
           </ul>
		      <!--<div class="btn-group">
                <a class="btn btn-inverse" href="#"><i class="icon-user icon-white"></i> User</a>
                <a class="btn btn-inverse dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>

                <ul class="dropdown-menu">-->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      </div>
 
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>EntreCommunity</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  

	</head>
		<body>
		
		 <%= render 'layouts/header' %>
			 <div class="container">
			 	<% flash.each do |name, msg| %>
			 		<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			 		<% end %>
	   
			<%= yield %>
			<%= render 'layouts/footer' %>




	         </div>
	         
		</body>
</html>


<!-- Modal -->
<div id="myModal1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Create A new Pin</h3>
  </div>
  <div class="modal-body">
    <p>
      



<%= render :partial => 'pins/form'%>




</p>
</div>
  
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel1">Create A new Status</h3>
  </div>
  <div class="modal-body">
    <p>
      



<%= render :partial => 'statuses/form'%>




</p></div>